import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from '../components/navbar'
import Gallery from '../components/body'
import React from "react";
import Global from '../global/global'
import Footer from '../components/footer'

export default function Home() {
  
  return (
    <>
    <Global>
      <Navbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <Gallery/>
        </div>
        <Footer/>
      </main>
      </Global>
    </>
  );
}
