import React from "react";
import Global from '../global/global'
import Head from "next/head";
import Navbar from '../components/navbar'
import Gallery from '../components/body'
import Footer from '../components/footer'


export default function Home() {
 
  
  return (
    <Global>
      <Navbar/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center flex-col">
          <Gallery/>
        </div>
        <Footer/>
      </main>
      </Global>
  );
}
